# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: None

version = 1
SPDX-PackageName = "oxygen-icons"
SPDX-PackageDownloadLocation = "https://invent.kde.org/frameworks/oxygen-icons"

# The icons.
[[annotations]]
path = ["16x16/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = [
    "2007 Nuno Pinheiro <nuno@oxygen-icons.org>",
    "2007 David Vignoni <david@icon-king.com>",
    "2007 David Miller <miller@oxygen-icons.org>",
    "2007 Johann Ollivier Lapeyre <johann@oxygen-icons.org>",
    "2007 Kenneth Wimer <kwwii@bootsplash.org>",
    "2007 Riccardo Iaconelli <riccardo@oxygen-icons.org>"
]
SPDX-License-Identifier = "LGPL-3.0-or-later"
